### PR TITLE
feat-#55: Implemented Slug Integration for Improved URL Sharing

### LINKED ISSUE #55: Introduce slugs to blog post URLs to make sharing easier
### Description

Currently, when I click on a post, the app routes to "/details-page" & displays the clicked post.

Now, if I want to share the post, naturally, I'll copy the URL & send it to the other person. 
Problem here is that, every post is having the same URL (which is [wanderlust-beta.vercel.app/details-page](https://wanderlust-beta.vercel.app/details-page)) 
& as of now if you go to that link, it throws 404.

To solve this, we can use techniques like using the ID of the post in URL, or maybe using something called "slug"

Current URL 
image

What I'm suggesting
image

### Use Case

As a reader of the blog,
It would be helpful to get the appropriate link of posts
So that it can be shared with other readers

### Proposed Solution

_No response_

### Additional Information

_No response_

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by vishalkumar9**
…ring (#55)

## Summary
Problem -  
**when you click on a post, the app routes to "/details-page" & displays the clicked post.
Now, if you want to share the post, naturally, you'll copy the URL & send it to the other person.
The problem here is that every post is having the same URL (which is [wanderlust-beta.vercel.app/details-page](https://wanderlust-beta.vercel.app/details-page))
& as of now if you go to that link, it throws 404.

In details-page
const {state} = useLoaction();
This line of code uses destructuring to extract the state property from the object returned by the useLocation hook. The state property contains any state data that was passed along with the navigation.

If someone shares a URL that includes state using React Router's state object, the state won't persist if you open that URL in another tab or directly enter it into the browser.

The state passed via location.state in React Router is specific to the current session and is not maintained in the URL itself. When you navigate directly to a URL that includes a state from an external source (like a shared link), React Router won't have that state information available, and location.state will be undefined.

## Description

To solve this, we can use techniques like using the postID in the URL, or maybe using something called "slug".

app js

post-card js

details js

So now If someone opens a blog or post from a shared URL the API request is sent to the backend to get post or blog data using ID.

The function createSlug takes a title string and converts it into a URL-friendly slug. The slug is typically used in URLs to represent the title in a format that's safe and readable within a URL.

## Images
Screenshot (42)

_Include any relevant images or diagrams that can help reviewers visualize the changes, if applicable_

## Issue(s) Addressed

- Closes #55

## Prerequisites

- [ ] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
@vishalkumar9, thank you for the PR,
Just couple of things to let you know,

1. Kindly first get the issue assigned to you and then work on the PR, so that there is no any overlapping efforts.
2. Try not to include images of code in the description
3. And kindly resolve the build failure and then request for review

Please go through the community guidelines one more time, so that things wouldn't be repetitive :)

**Comment by krishnaacharyaa** [comment]
@kuldeepjambhulkar, would love to have your review here, if you are willing to :)

**Comment by vishalkumar9** [comment]
@krishnaacharyaa hey I have fix the build error there are some minor conflicts can you look into it

**Comment by krishnaacharyaa** [comment]
@vishalkumar9 Can you rebase your branch, kindly follow the contributing guidelines, it is caused due to merge conflicts

**Comment by krishnaacharyaa** [comment]
I suggest you create new branch, and close this branch, would be much better

**Pull request closed without merging**
