### PR TITLE
Added 404 Not Found Page 

### PR DESCRIPTION
**Pull request by Mayur-666**

### CODE REVIEW

**Comment by Mayur-666** [comment]
@krishnaacharyaa I have opened the request please review it.

**Comment by krishnaacharyaa** [comment]
Okay @Mayur-666 , 
2 things
1. Contributing guidelines aren't followed in both PR description and commit messages, kindly recreate the PR
2. Let's not worry anything about the user is logged in or not in the 404 page, it should just server if there is no any other route, that's it. 

Closing this PR with above commit

**Comment by Mayur-666** [comment]
Are there any docs regarding the guidelines, i'm not aware of it @krishnaacharyaa

**Comment by Mayur-666** [comment]
should i also remove the login button from 404 page @krishnaacharyaa

**Pull request closed without merging**
