### PR TITLE
fix-#445: Absence of a Proper Loading skeleton for the AddBlog Section #pr446

### LINKED ISSUE #445: [BUG] Absence of a Proper Loading skeleton for the AddBlog Section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Present  Loader widget is unresponsive and not matching the website theme
Image

### Expected Behavior

The AddBlog section should have a proper loading skeleton that is responsive and theme accurate.

### Reproduction steps

```bash
1. Login in
2. Click on Add Blog button
3. Notice the error
```

### Screenshots

Proposed design
Image

### Logs

_No response_

### Browsers

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by MetiUmashri**
## Summary

This PR provides a Loading Skeleton for the AddBlog section so that the user has a seamless experience

## Description

AddBlogPostSkeleton Component has been added and has been used to replace the previous Loader component that was used.

## Images

image
image

## Issue(s) Addressed

Closes #445
Enter the issue number of the bug(s) that this PR fixes

Template should be strictly Closes <issue_number>
Example: Closes Centralised Error Handling #1

## Prerequisites

- [ X] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by MetiUmashri** [comment]
i have made the changes

**Comment by krishnaacharyaa** [comment]
Please add snapshots of both the loaders

**Comment by MetiUmashri** [comment]
i have added the screenshots, in the below screenshot of the loader working the footer is also seen, my screenshot is unable to capture it. But in both the loaders the footer is seen. @krishnaacharyaa  i have added the screenshots.

**Comment by krishnaacharyaa** [comment]
Hey sorry yaar @MetiUmashri , i thought i had commented, figured out i hadn't published it was in pending state, sorry for that, a bit busy with workplace, excuse me for the delay

**Comment by AMS003010** [comment]
Hey @krishnaacharyaa 

@MetiUmashri  and I thought of improving the next loader in a different PR 😁
Both of us would like to work on this as well....

**Pull request merged**
