### PR TITLE
enhance: #28 long time to load bg image

### LINKED ISSUE #28: Fix the homepage bg image long load time
The background image of a beach scenery behind the logo on the homepage is currently hosted in JPG format. It takes a significant amount of time to load, even on a fast internet connection. To address this issue, I have hosted the image on imgbb in WebP format. The resolution remains the same, but now, due to its WebP format, the image loads quickly, virtually instantaneously. I kindly request you to assign this issue to me.

### PR DESCRIPTION
**Pull request by jjinendra3**
## Summary
Changed the jpeg bg image to webp file eliminating 5-6 seconds and crucial resources that was being taken to load a bg image.

## Description
Hosted the converted jpeg to webp file on imgbb to save on the overall build site keeping in mind that we will never the chanage the bg image, the home page now loads much faster and looks better.

## Images
[OLD AND NEW GIFS](https://drive.google.com/drive/folders/1p8ZtBz0ykdiUA2-KEQi7BMzymZgbyjZi?usp=drive_link)

## Issue(s) Addressed
_Enter the issue number of the bug(s) that this PR fixes_
- Template should be strictly **Closes #28 **
- Example: Closes #1

## Review Checklist
Please make sure to go through this checklist before submitting your review.

- [ x] Make sure the PR title is of format **`tag: Issue Title`**
   - tag should be one of `fix`,`feat`, `docs`, `chore`, `refactor`
   - Ex: `feat: Added responsive design for the home page`
- [ x] Ensure the code follows our coding standards and guidelines
   - Ex:  naming conventions should be of form `file-name.ts` not `fileName.ts`
- [ x] Ensure that you have staged only the required commits and raised the PR and not included all the files which would be otherwise required for local setup
- [ x] Check if the PR is rebased to the latest main/development branch.
- [ x] Make sure there are no unnecessary files or debugging artifacts in the PR.

### CODE REVIEW

**Comment by jjinendra3** [comment]
Hey @krishnaacharyaa ,tried to create a new pr following the given pr template, and for the previous commits , im a little new at git for now, i have tried my best to do as you mentioned but if it is still not as it should be, please inform me for the same ill try to do more research about it and create  a new pr..... Thanks, any kind of feedback will be greatly appreciated

**Comment by krishnaacharyaa** [comment]
Thank you @jjinendra3, for your sincere efforts I really appreciate the time and efforts put into storing the gif into google drive and sharing the link, which was not expected, thank you for the efforts.

Just some points to share if you already didn't know,
- You can minimize all the efforts by directly embedding gif in the md file like https://stackoverflow.com/questions/34341808/is-there-a-way-to-add-an-animated-gif-to-a-markdown-file this will greatly save your time and efforts for coming future.
- And coming to the git part sure, I'll be more than happy to help you.

Some observations
- Why does it say it closes 1st issue ? 
- And small spacing issues in the [ x] it should have been [x]

**Comment by krishnaacharyaa** [comment]
To answer the git part
I have tried to explain the present scenario to the best according to my understanding about git, please feel free to go through you might have to do some research on top of it, I have just tried to give you overall understanding, hope it helps.
If there is still more questions to ask, we can have a call.
Please go through and if you further find nice articles about git feel free to share, there's always more things to learn :) 

image

**Comment by krishnaacharyaa** [comment]
Just one thing to keep in mind you can use this as reference dont take my word for it, sometimes some part even I might have missed, feel free to let me know if any. Happy to correct myself and learn :)
And you might have to close this PR and raise new PR for this as per my understanding, feel free to explore what is the best solution :) You know what I would do now :)

**Comment by jjinendra3** [comment]
Hey @krishnaacharyaa ,

I wanted to take a moment to express my sincere thanks your efforts that have helped me grow and learn, not only about Git/GitHub but also about the MERN stack. 

The guidance and knowledge you've shared is something I genuinely appreciate.

Now, I plan to create a new pull request and will try incorporate all the changes you've mentioned. 

Thank you once again for your guidance and the opportunity to contribute to this project.

**Comment by krishnaacharyaa** [comment]
@jjinendra3 Thank you for your kind words 😇 Always happy to share and I am glad to hear that it is greatly helping you :)

**Pull request closed without merging**
