### PR TITLE
refactor: Created a new header-layout file to segregate out header code.

### PR DESCRIPTION
**Pull request by Mohitsen11**
## Summary

This PR introduces modular approach by separating header-code in a new 'header-layout' file  rather than keeping into a single file (home-page).

## Description

This PR isolates the header-related code from the home-page file and moves it into a new header-layout file, along with all imported modules. It then integrates this header-layout as a component within the home-page file.

## Images

_Include any relevant images or diagrams that can help reviewers visualize the changes, if applicable_

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Review by krishnaacharyaa — COMMENTED** [review]
Please run `npm run format` in the frontend folder and commit

**Comment by Mohitsen11** [comment]
> Please run `npm run format` in the frontend folder and commit

Done.

**Review by krishnaacharyaa — APPROVED** [review]
Thank you @Mohitsen11 For the quick response :)

**Comment by Mohitsen11** [comment]
> Thank you @Mohitsen11 For the quick response :)

Thank you, @krishnaacharyaa, for guiding and helping me to learn best practices.

**Pull request merged**
