### PR TITLE
[ENHANCEMENT] issue49 Add button inside image url input to generate random images #49

### LINKED ISSUE #49: [ENHANCEMENT] Add button inside image url input to generate random images
### Description

Presently, people who want to test are not patient enough to make efforts to find a valid image from the website and then upload, so they normally end up in something like `demo.png`, our regex passes and then image is not loaded in the home page, so we need to have array of 10 perfect working images preferably of webP fromat as it loads faster, and when `generate random` button is clicked one of the 10 images url form the array should get auto filled.

### Current Behavior

We can have invalid images like demo.png when creating a post

### Proposed Enhancement

Add a button `generate random image url` in the textbox of image url which autofills with the perfect image from array of image urls 

### Use Case

It helps in enhancing UI of the app, so we don't see broken images in the app

### Blockers

_No response_

### Additional Information/ Attachments

_No response_

### PR DESCRIPTION
**Pull request by jjinendra3**
## Summary
Updated image modal to allow users to select any of the 7 images from the webp format instead of randomizing.

## Description
In this pull request, I've modified the image modal functionality to enhance user experience. Now, users can specifically choose from any of the 7 available images in the webp format instead of the previous randomization. This change was implemented to give users more control over the visuals they want to interact with.

## Images
https://drive.google.com/drive/folders/14JFGZFLu-vtUvZdi7CmX4zrihCY0Lv21?usp=sharing

## Issue(s) Addressed
Closes #49 

## Prerequisites
- [x] Have followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)

### CODE REVIEW

**Review by krishnaacharyaa — CHANGES_REQUESTED** [review]
It was a quick update @jjinendra3, thank you, kindly rebase your branch and address the comment :)

**Comment by krishnaacharyaa** [comment]
@jjinendra3 , the build is failing, please address that :)

**Comment by jjinendra3** [comment]
Hey it seems like there are some merge conflicts in the PR, i think it would be best to open a  new PR for this.

**Comment by krishnaacharyaa** [comment]
Yes please :) Feel free to create a new one

**Pull request closed without merging**
