### PR TITLE
form handling using react hook form

### PR DESCRIPTION
**Pull request by NirbhaySingh74**
## Summary

Added react hook form.

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
Please rebase the branch and solve the merge conflicts

This the error because of which the deployment is failing,
image

@devsharmagit please help him and review the code if things are working fine

**Comment by krishnaacharyaa** [comment]
Please follow everything said in the discord

**Comment by krishnaacharyaa** [comment]
@NirbhaySingh74 do we have any updates on this?

**Comment by NirbhaySingh74** [comment]
Need help to raise pr

**Comment by krishnaacharyaa** [comment]
Closing this as lack of inputs to help out. "Failed to raise PR" "Need help to raise PR" doesn't clearly say where you are stuck at and what problem you are facing, and we expect you to actively thrive to figure that out or actively ask anyone of us.

**Comment by NirbhaySingh74** [comment]
could you Join google meet to help me to raise pr in proper way?

**Comment by krishnaacharyaa** [comment]
Sure @NirbhaySingh74, I would happy to do so, but i couldn't find active interest from your side unfortunately. So had to close this. But now if you have interest and can actively follow through and want to learn, I'll be happy to help...

Before call can you kindly go through the contributing guidelines properly and try to understand the things. From here: https://github.com/krishnaacharyaa/wanderlust/blob/e9a438271e757d69777a9d0ba7799f837ad13ab7/.github/CONTRIBUTING.md#request-for-changespull-requests

Once you have tried and know what all you didn't get, note it down we'll discuss in the call. Kindly try to understand git... It will help you to understand things better when we are in call....

p.s: If you are ready to put your efforts, I'm happy to help :)

**Comment by NirbhaySingh74** [comment]
i had follow these steps but don't know where the problem is?

**Comment by krishnaacharyaa** [comment]
> i had follow these steps but don't know where the problem is?

Revaluate your statement on 2nd and 3rd points in  https://github.com/krishnaacharyaa/wanderlust/blob/e9a438271e757d69777a9d0ba7799f837ad13ab7/.github/CONTRIBUTING.md#guidelines-for-contributions

The git thing I can teach you ... if that is the problem but there is the problem in the existing PR.


Easy step would be 
Delete project and clone again, and follow above guidelines and raise PR, you should ideally not face any problem

**Pull request closed without merging**
