### PR TITLE
Bug#172

### LINKED ISSUE #172: [BUG] Login of the user doesn't stay if I refresh the page ( Non - consistent )
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I login and then refresh the page, it immediately shows me that I am logged out and asks me to login in again, where as according to the logic it should have waited for 4mins and only after 4mins it should have showed me to login again

### Expected Behavior

Until it has hit four minutes I shouldn't be logged out after refresh

### Reproduction steps

```bash
1. Go to https://wanderlust-beta.vercel.app/
2. Register/Login 
3. See the create-post and logout button
4. Refresh the page.
5. You'll again see the login button
```

### Screenshots

Login and after Refresh

image

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by Ameerjafar**
## Summary

_Briefly describe the purpose of this PR._

## Description

_Explain in detail what this PR is all about. This should include the problem you're solving, the approach taken, and any technical details that reviewers need to know._

## Images

_Include any relevant images or diagrams that can help reviewers visualize the changes, if applicable_

## Issue(s) Addressed

_Enter the issue number of the bug(s) that this PR fixes_

- Template should be strictly **Closes <172>**
- Closes #172 

## Prerequisites

- [ yes ] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by Ameerjafar** [comment]
@krishnaacharyaa can you review this pr sir

**Comment by 0xmohitsen** [comment]
> @krishnaacharyaa can you review this pr sir

Thanks for the PR. @Ameerjafar

Do these also :- 1. Apply the same thing in the signup-page.tsx that is done in signin-page.tsx.

Q1. If we are now storing cookies( accessToken, refreshToken) in browser then what is the use of UserState singleton class in frontend that is storing the accessToken in state variable?

**Comment by 0xmohitsen** [comment]
> ## Summary
> _Briefly describe the purpose of this PR._
> 
> ## Description
> _Explain in detail what this PR is all about. This should include the problem you're solving, the approach taken, and any technical details that reviewers need to know._
> 
> ## Images
> _Include any relevant images or diagrams that can help reviewers visualize the changes, if applicable_
> 
> ## Issue(s) Addressed
> _Enter the issue number of the bug(s) that this PR fixes_
> 
> * Template should be strictly **Closes <172>**
> * Closes [[BUG] Login of the user doesn't stay if I refresh the page ( Non - consistent ) #172](https://github.com/krishnaacharyaa/wanderlust/issues/172)
> 
> ## Prerequisites
> * [ yes ] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

@Ameerjafar Try to fill the given details. 

Always remember if default PR template is given, try to fill it. 
It is given for a purpose to make everyone understand what this PR is all about.

**Comment by Ameerjafar** [comment]
@0xmohitsen Q! As of now can I remove the userState singleton class from the signin and signup component.

**Comment by 0xmohitsen** [comment]
> @0xmohitsen Q! As of now can I remove the userState singleton class from the signin and signup component.

Go ahead, let's see what you are upto?

**Comment by Ameerjafar** [comment]
@0xmohitsen Without the singelton class of userstate we cannot set the cookie in the access token immediately that is the reason we are using the userState singleton class sir.

**Comment by 0xmohitsen** [comment]
> @0xmohitsen Without the singelton class of userstate we cannot set the cookie in the access token immediately that is the reason we are using the userState singleton class sir.

Yeah!!

**Comment by 0xmohitsen** [comment]
> @0xmohitsen Without the singelton class of userstate we cannot set the cookie in the access token immediately that is the reason we are using the userState singleton class sir.

There is a problem here.

1. When accessToken expires they removed from browser's cookie but still user is able to create post. While user must not be able to create post when tokens are expired and removed from browser's cookie.

**Comment by Ameerjafar** [comment]
@0xmohitsen  can you now review the pr sir.

**Comment by 0xmohitsen** [comment]
> @0xmohitsen once the accessToken expiry after the refresh only the website logged out that is the way the existing code had written sir.

@Ameerjafar User is not able to create blog post when tokens are expired and redirects to homepage as expected but there is no conditional rendering. We want to display login button when tokens are expired.

**Comment by 0xmohitsen** [comment]
> > @0xmohitsen once the accessToken expiry after the refresh only the website logged out that is the way the existing code had written sir.
> 
> @Ameerjafar User is not able to create blog post when tokens are expired and redirects to homepage as expected but there is no conditional rendering. We want to display login button when tokens are expired.

But currently we are displaying create post + logout button which is not correct.

**Comment by Ameerjafar** [comment]
@0xmohitsen ok sir let me work sir.

**Comment by krishnaacharyaa** [comment]
@Ameerjafar Thank you for the PR, kindly close this PR and let's stragtegize what to be done and then raise new PR with proper commit message and PR description. Slow down and follow the guidelines, which is repeatedly told, https://github.com/krishnaacharyaa/wanderlust/blob/9b11b769bb23150b746296cf9008056633d21921/.github/CONTRIBUTING.md#guidelines-for-contributions. 
Closing this PR because of improper commit message and non PR details.

**Pull request closed without merging**
