### PR TITLE
Update signup-page.tsx CSS

### LINKED ISSUE #396: improvement in css of login page in mobile view / responsiveness
### Description

image

css of login page in mobile view not look good i can fix it

### Current Behavior

all elements are added on top of page

### Proposed Enhancement

username and password section should be centralized

### Use Case

It will enhance look in mobile view and it will increease ui/ux of website

### Blockers

_No response_

### Additional Information/ Attachments

_No response_

### PR DESCRIPTION
**Pull request by dhairyagothi**
## Summary
fixed Signup page CSS in mobile view _

## Description

_before 
image

after
image

## Images

_Include any relevant images or diagrams that can help reviewers visualize the changes, if applicable_

## Issue(s) Addressed

closes #396 

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by dhairyagothi** [comment]
please merge PR with gssoc label and assign me

**Comment by krishnaacharyaa** [comment]
Hi @dhairyagothi kindly take some time and follow https://github.com/krishnaacharyaa/wanderlust/blob/6fa9d7768d6f709abbb7599b7680b27e1f325f5b/.github/CONTRIBUTING.md#guidelines-for-contributions.

And make sure we have 16px of padding left and right , use the tailwind equivalent i guess `p-4` and no hardcoding of px values please.

p.s: You might have to raise a new PR because the commit doesn't follow the guidelines! I wonder how you were able to bypass the husky pre-hooks ....

**Comment by krishnaacharyaa** [comment]
@dhairyagothi can you kindly address the PR comments

**Comment by dhairyagothi** [comment]
> Hi @dhairyagothi kindly take some time and follow https://github.com/krishnaacharyaa/wanderlust/blob/6fa9d7768d6f709abbb7599b7680b27e1f325f5b/.github/CONTRIBUTING.md#guidelines-for-contributions.
> 
> And make sure we have 16px of padding left and right , use the tailwind equivalent i guess `p-4` and no hardcoding of px values please.
> 
> p.s: You might have to raise a new PR because the commit doesn't follow the guidelines! I wonder how you were able to bypass the husky pre-hooks ...., Haven't you actually setup the project? Because pre-hooks should ideally not allow you to commit, the commits which are not following the guidelines

okay sure i am making things coorect give me few moments

**Comment by dhairyagothi** [comment]
making new PR

**Comment by krishnaacharyaa** [comment]
@dhairyagothi where are we?

**Comment by dhairyagothi** [comment]
> @dhairyagothi where are we? 

Husky is not running in my local system

**Comment by krishnaacharyaa** [comment]
@dhairyagothi where you able to figure out the root cause? Have you properly followed the instructions made in the readme and setup the project ?

**Comment by krishnaacharyaa** [comment]
@dhairyagothi

**Comment by krishnaacharyaa** [comment]
@dhairyagothi Hi, are still interested in this issue? 
Or can i assign to someone elese

**Pull request closed without merging**
