### PR TITLE
Fixed #28 (HomePage Load TimeTaking)

### LINKED ISSUE #28: Fix the homepage bg image long load time
The background image of a beach scenery behind the logo on the homepage is currently hosted in JPG format. It takes a significant amount of time to load, even on a fast internet connection. To address this issue, I have hosted the image on imgbb in WebP format. The resolution remains the same, but now, due to its WebP format, the image loads quickly, virtually instantaneously. I kindly request you to assign this issue to me.

### PR DESCRIPTION
**Pull request by jjinendra3**
As discussed in the comments of issue ** #28 **, i have used the url approach

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
Thank you @jjinendra3, for the PR, kindly make the following changes,,
1. Follow the PR template, I understand it is a small change, but we still prefer following the PR template, as it is a standard and helps in a long run and I would be more than happy to see a small GIF of how effective is the change in the images section of the PR template
2. Kindly branch out from the latest master branch, this present branch is contains previous commits which is not ideal.
     set upstream branch to this project
     git pull upstream master in your forked project
     Create a branch in your forked project
     Make the commit and push
     And raise PR from that branch

**Comment by krishnaacharyaa** [comment]
Feel free to document if possible the above steps, will soon create a contribute.md file which would be really helpful there,
If you are interested in taking that up, feel free to raise an issue, I'll get it assigned to you, else I'll get it done myself no worries anyways...

**Comment by jjinendra3** [comment]
> Thank you @jjinendra3, for the PR, kindly make the following changes,,
> 
> 1. Follow the PR template, I understand it is a small change, but we still prefer following the PR template, as it is a standard and helps in a long run and I would be more than happy to see a small GIF of how effective is the change in the images section of the PR template
> 2. Kindly branch out from the latest master branch, this present branch is contains previous commits which is not ideal.
>    set upstream branch to this project
>    git pull upstream master in your forked project
>    Create a branch in your forked project
>    Make the commit and push
>    And raise PR from that branch

it seems like i will have to create a new branch for the same! will do it, closing this pr!

ps. i think i wont be able to serve justice in creating the contribute.md but can surely suggest changes for the same once its made :)

**Comment by krishnaacharyaa** [comment]
@jjinendra3, I understand, thank you for the acknowledge, feel free to share your views once the contribute.md is created :)

**Pull request closed without merging**
