### PR TITLE
fix-#362: Anchor tag added in the logo

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
## Summary

anchor tag added in the logo

## Description

_Explain in detail what this PR is all about. This should include the problem you're solving, the approach taken, and any technical details that reviewers need to know._

## Images

https://github.com/krishnaacharyaa/wanderlust/assets/125277258/8e4c974a-81dd-41c8-af39-f7bacf44cc6a

## Issue(s) Addressed
#362 solved

- Template should be strictly **Closes <issue_number>**
- Example: Closes #1

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
Kindly read what is already reviewed @RamakrushnaBiswal

**Comment by krishnaacharyaa** [comment]
By the bot @RamakrushnaBiswal

**Comment by RamakrushnaBiswal** [comment]
@krishnaacharyaa done😮‍💨

**Comment by krishnaacharyaa** [comment]
@RamakrushnaBiswal do we actually require <a> tag? Can we come up with a alternate tag which react recommends? 
And kindly follow the commit guidelines... :)

**Comment by RamakrushnaBiswal** [comment]
Link  ? @krishnaacharyaa

**Comment by krishnaacharyaa** [comment]
> Link ? @krishnaacharyaa

Go for it

**Comment by RamakrushnaBiswal** [comment]
@krishnaacharyaa done bro

**Review by krishnaacharyaa — APPROVED** [review]
LGTM, thanks

**Comment by RamakrushnaBiswal** [comment]
hi @krishnaacharyaa Thank you for accepting the PR ,please add some labels and assignee for me 🥹🥹

**Comment by RamakrushnaBiswal** [comment]
@krishnaacharyaa labels like label 1,label 2 ,label 3

**Comment by krishnaacharyaa** [comment]
As it is small change and you havent followed community guidelines i havent put the label @RamakrushnaBiswal

**Comment by RamakrushnaBiswal** [comment]
@krishnaacharyaa its okey

**Pull request merged**
