### PR TITLE
BUGFIX-#193: User can access undefined routes.

### LINKED ISSUE #193: [BUG] User can access undefined routes.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, when a user tries to hit routes like "https://wanderlust-beta.vercel.app/hgdf" ( "https://wanderlust-beta.vercel.app/undefined-routes") the application does not handle undefined routes gracefully and simply displays a page which displays footer.

Screenshot 2024-05-11 153527

### Expected Behavior

When navigating to undefined routes such as http://localhost:3000/iughdfugh, I expect to be redirected to a 404 Page Not Found error page. 

Reference Imag
error-page
e:-

### Reproduction steps

```bash
1. Go to 'https://wanderlust-beta.vercel.app/'
2. Search on 'https://wanderlust-beta.vercel.app/whatever-you-like'
3. See error
```

### Screenshots

DESCRIPTION

### Logs

```bash
Steps to Implement:

1. Create a 404 Page Not Found component if not already existing. This component should display a user-friendly message informing users that the requested page cannot be found.
2. Define a route for undefined paths in the router configuration (e.g., React Router). This route should match any undefined paths and render the 404 Page Not Found component.
3. When a user navigates to an undefined route, the router should automatically redirect them to the 404 Page Not Found component.
4. Test the implementation thoroughly to ensure that accessing undefined routes correctly redirects users to the 404 error page.
5. Add appropriate styling and design to the 404 Page Not Found component to enhance user experience.
```

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by Mayur-666**
## Summary

Added 404 not found page with 3d links in the background.

## Description

This PR  resolves issues for undefined routes.
Previously there was an empty page when user enters any undefined url.
But now a beautiful Error page is added.

## Images

Screenshot (532)
Screenshot (533)

## Issue(s) Addressed
 Closes #193

## Prerequisites

- [✓] Have you followed all the [CONTRIBUTING GUIDELINES]

### CODE REVIEW

**Comment by Mayur-666** [comment]
Also removed login concerns from Error Page

**Comment by Mayur-666** [comment]
Sorry! @krishnaacharyaa  I'll not repeat commit mistake again.

**Comment by krishnaacharyaa** [comment]
@Mayur-666 
couple of suggestions, 

Can you reduce the padding or height of the appbar, ideally just give p-4 or p-8 don't hardcode any value for height of the appbar.
And can you reduce the pace of the things moving around so it looks subtle
and set opacity to the bg of the appbar, so the things which are moving around will move around behind appbar even similar to the footer.

**Comment by krishnaacharyaa** [comment]
And make sure the "wanderlust" is at the same place when in proper page and in error page, it shouldn't seem like it is shifting its position. basically have same px values

**Comment by Mayur-666** [comment]
Ok

**Comment by krishnaacharyaa** [comment]
And bonus, if you create a new PR with proper PR and commit and all the required changes requested. I'll give 3level, because it involved a bit of work and I'm fine giving it anyways, as far as you are actively interested in doing things :)

**Pull request closed without merging**
