### PR TITLE
chore: Update all node dependencies; do some after-update tasks

### PR DESCRIPTION
**Pull request by chinmaykunkikar**
## Summary
Update all eligible dependencies and complete a couple of tasks to make sure nothing breaks. 

## Description
- This PR will update all dependencies in `frontend` and `backend`.
- Remove `dotenv` from frontend dependencies since it wasn't being used and Vite already handles environment variables, which we already use.
- (Task 1) Since it updates `mongoose` to the next major version (v8.0.0), I have made sure that I follow the [official migration guide](https://mongoosejs.com/docs/migrating_to_8.html) provided by the developers of the library. Read more in the related commit description: https://github.com/krishnaacharyaa/wanderlust/pull/56/commits/d4d8ca9bd6d68f1ce5f169123060f34cc0c071fc 
- (Task 2) Since prettier also got a minor update, I thought it will be a good idea to run `prettier` on all files of `frontend` (`backend` code is already good) to format all the files that are outside the `src` directory. It has fixed the formatting issues of these files.

## Images
_N/A_

## Issue(s) Addressed
_N/A_

## Prerequisites
_N/A_

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by chinmaykunkikar** [comment]
@krishnaacharyaa if you're up for it, I'd like to recommend adding a handy plugin: [prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss). It automatically sorts tailwind classes according to tailwind's conventions. This prevents writing overriding classes by mistake and generally makes the codebase better. I've been using it personally for a year now.

Read more about it in the announcement blog article: https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

If you're up for it, I can add the dependency and add that commit to this PR itself as it is more of a refactoring issue.

**Review by krishnaacharyaa — APPROVED** [review]
Thank you @chinmaykunkikar for updating the dependencies, it's very useful.

Just one point i would like to discuss with you:
When you said that you ran the prettier outside `.\src` did you mean that you manually ran a script or manually went through all the files and formatted ?
   Because in the `package.json` of frontend we have `"format": "prettier --write ./src"`, so replacing "./src" by "." should ideally serve our purpose( I unknowingly missed it while adding the script)  
   Could you kindly update that.
   
And may be in the near future when we setup a CI/CD pipleine we can run this script so that we maintain consistency :)

**Comment by chinmaykunkikar** [comment]
> When you said that you ran the prettier outside `.\src` did you mean that you manually ran a script or manually went through all the files and formatted ? Because in the `package.json` of frontend we have `"format": "prettier --write ./src"`, so replacing "./src" by "." should ideally serve our purpose( I unknowingly missed it while adding the script).

Yes, I ran it manually since, like you pointed out, package.json on script only runs prettier on `src` dir.

> Could you kindly update that.

Sure! On it.

**Review by krishnaacharyaa — APPROVED** [review]
Thank you @chinmaykunkikar, LGTM, merging now :)

**Pull request merged**
