### PR TITLE
fix: Decreasing the loading time of the application #12

### PR DESCRIPTION
**Pull request by jjinendra3**
## Summary
This PR aims to enhance the performance of the website by implementing various optimization techniques. It includes image format conversion to WebP, backend file compression with Gzip, and the removal of unused react-icons package and converting the icons to PNG images. These changes are designed to improve loading times and user experience.

## Description

- Image Optimization: I have updated sample data image files to use the WebP format, which offers superior compression, reducing image sizes for faster loading.

- Backend File Compression: I have introduced a compression package to convert backend files into gzip format, significantly reducing file sizes during transmission and speeding up the website.

- Icon Optimization: react-icons were found to be consuming excessive resources, that lead me to replace them with plain PNG images. Furthermore, I have removed the react-icons page from the project, eliminating unused package taking up internet resources and improving loading times.

## Images
https://ibb.co/5s1WNNg
https://ibb.co/87jktc2
https://ibb.co/Vv7yS4f

## Issue(s) Addressed
Closes ** #12 **

## Prerequisites
- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
Hi @jjinendra3, thank you for your intensive research and unique solution, very much appreciated.

Just some clarifications:
1. "Backend File Compression: I have introduced a compression package to convert backend files into gzip format, significantly reducing file sizes during transmission and speeding up the website." Can you explain a little more this ? Like how does this happen for every run it bundles or we have to manually run some scripts or it automatacilly reduces, the "during transmission" part is little unclear to me.
2. If you didn't know already in github you can copy image and directly paste it will upload to github cloud and then showcase because currently it is hard to go elsewhere and find the image, ex take a screenshot and copy the image to clipboard and directly paste it here, rest leave it to github , so it will be very handy and the preview is very helpful right away in the same page.
3. Can you kindly also add the latest lighthouse scores, would be very handy
4. And as previously said, i have loosened the authorization part, so ideally if you try to commit and push to this branch from now on it should auto deply and should not fail and wait for my approval, any issues related to that kindly let me know :)

**Comment by jjinendra3** [comment]
Sure @krishnaacharyaa 

Gzip is a widely used file compression format. When applied to web content, it reduces the size of files (e.g., HTML, CSS, JavaScript) before they are sent to the client's browser. This compression is applied automatically by the server when it sends files to the browser. Users don't need to run scripts or take any manual actions; it's a behind-the-scenes optimization that helps improve website performance by reducing file sizes and speeding up content delivery.

When I measure the Lighthouse performance on my device, it shows a low score of 84 due to the localhost (vite bundle) (acc to lighthouse). However, when I checked the deployed website, the primary reason for the delay is related to the jpg images, which I have since fixed. Currently, the Lighthouse performance score on localhost is 84, but I believe the actual performance is better which we can accurately measure when we deploy the changes on production, also @krishnaacharyaa , please note that since the sample-data.json is changed, you might have to manually upload it again in your mongodb cluster.

Image

**Comment by krishnaacharyaa** [comment]
@jjinendra3 Thank you for the detailed explanation, yeah will surely redeploy the builds once i update in the remote mongodb cluster, and let you know once done

**Comment by krishnaacharyaa** [comment]
image

There is a decent increase in the performance

However for mobile it is a bit discouraging
image

But in my opinion it is fine for mobile, i think it is majorly because the website is not yet compatible with the mobile screens, during that issue we can look into this,

But can we focus on desktop one other day and see if there is any further improvments we could do, if not we can merge the issue, but i strongly feel 1 more day we can try, what do you say @jjinendra3 ?
Let me know your thoughts on what can be done , the deployed url is https://wanderlust-g2a7kl4pz-krishnaacharya-official.vercel.app/

**Comment by krishnaacharyaa** [comment]
Can we once try using the main background image via assets page ? It might increase build size a little, but i guess can be rendered quicker, we can give it a try and compare, because inhouse are always faster than getting it from internet, can we give it a try ?

**Comment by jjinendra3** [comment]
Sure @krishnaacharyaa , I will try and send you the results.

**Comment by jjinendra3** [comment]
deployed-perfomance


As I mentioned earlier, my approach is effective, as it is yielding a good performance score and when we look into the places where we can improve according to lighthouse, localhost no more appears.

Also i have made another commit and now the bg image is a part of asset as opposed to being a cdn.

**Comment by krishnaacharyaa** [comment]
Hi @jjinendra3, 100% is awesome, Thank you and congrats on making it possible, can you just let me know how to reproduce that, on which browser git you get and did using the bg image from asset helped you ?

I doubt that because in the vercel.json we have to explicitly specify the public static files for the vercel build to know and load it from the static folder, that i will get it done no worries, may be tomorrow when you are free let me know, we'll sit together and get this done, because i feel the assets should be ouside src folder under public folder, i am not finding supporting document to add as reference here, in gist it is basically having the public static files ready to use in the browser, it will be available in the resources section of the deployed website in the assets folder, we'll look into that. other than that LGTM

**Comment by jjinendra3** [comment]
Hey @krishnaacharyaa , what I noticed by running lighthouse multiple times that now on this website it has just become a internet speed tester because, higher the internet speed is, higher is the performance because basically the time taken by the image cdn to load is the only thing that may cause a performance lag and faster the image load, faster is the performance, so as opposed to jpeg which has massive sizes, webp files have helped hit 100% due to its low size and highly web compatible nature.

Also, making bg an asset has helped the website look good when opening it, because previously it took some amount to load but now it's instantaneous, that is, it loads with the website.

**Review by krishnaacharyaa — APPROVED** [review]
LGTM :)

**Comment by krishnaacharyaa** [comment]
@jjinendra3 Thats awesome to here :) Yeah the bg as an asset was a nice call, and the conversion of jpg to webP is awesome idea, thank you @jjinendra3 :) seems like some issue previously when i tried opening the link, now i can see updated lighthouse scores as provided by you, atleast similar...
image
Now i can see it as an asset.

I would want to consider the tradeoffs of using the assets in the src folder, because normally we store it outside the src in public folder, may be in future scope we can look into that, this fix would suffice for this PR.
I'm closing this as resolved now

**Comment by krishnaacharyaa** [comment]
@jjinendra3 please make sure the commits are following the guidelines as it shows in the commit of the project, I understand it happens unintentionally, will try to put some checks before getting merged as even i miss sometimes :)

**Pull request merged**
