### PR TITLE
fix-#80 ui button issue solved

### LINKED ISSUE #80: UI - small button on the latest post card redirecting back to normal tab
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when clicking on that button , it redirects back to a normal tab
[screen-capture.webm](https://github.com/krishnaacharyaa/wanderlust/assets/116346644/80c727cd-bf31-4d91-9932-4c1b9b4ad870)

### Expected Behavior

it should open the specific blog or it should open the specific  blog in a new tab

### Reproduction URL

https://github.com/mohamedshamil7/wanderlust

### Reproduction steps

```bash
1. Go to https://wanderlust-beta.vercel.app
2. Click on  the small button on the top right corner of the latest post card
3. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

_No response_

### Browsers

Chrome, Safari

### OS

Mac

### PR DESCRIPTION
**Pull request by mohamedshamil7**
## Summary

Ui - button on the latest post card redirecting to a empty tab solved 

## Description
 button on the latest post card redirecting to a empty tab solved . Removed the navigation functionality
 

## Issue(s) Addressed

Closes #80 

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Review by krishnaacharyaa — CHANGES_REQUESTED** [review]
Why all this? circus, can't we simply navigate? or something like we dont let the user to click this by making it unclickable, 

At the least we can just remove away this navigate(-1) then nothing will happen :)

**Comment by mohamedshamil7** [comment]
there are multiple ways to solve the issue , either we could just remove that button or use it to open the blog in a new page . Leaving that button with no function will not be a good way to solve the issue . Making that button to open the blog in the same page will also be useless as we are already using the navigate fn on the main div . 

i thought of opening the blog in a new tab would be effective and added the function to do so .  I read using "target:_blank" directly might have some security concerns . Please correct me if  I am wrong ! .

I Could directly navigate to the new tab or simply just remove the button . Both options feel right to me . can you suggest your opinion ?

**Comment by krishnaacharyaa** [comment]
@mohamedshamil7 lets not complicate this 
image

The very obvious fix would be just copy pasting Line No: 14's onclick to 22's onclick, that will solve the issue.

I just want you to explore if there is any other way of doing this, by which i mean,
Now the button is the child of the parent div in which the navigation is working perfectly fine right?
There may be some way that we may this button's click of no effect and letting it work simply like the parent, you can try just by removing the onclick, see if the existing parent's click works.

I really appreciate your thoughts and creativeness of opening in a new tab, but we would ideally don't want that much of complexity presently, and the present PR doesn't actually work as per your fix.
image

**Comment by mohamedshamil7** [comment]
As per your suggestion i think at present there is no much use of that button . I guess i will remove the navigate functionality from the button

**Comment by krishnaacharyaa** [comment]
Yeah it is just to indicate that if you click this post you'll go to the details, as said in discord, it is for UX, showpiece basically.
It alone doesn't have any functionality

**Review by krishnaacharyaa — APPROVED** [review]
Yeah that's it :)

**Pull request merged**
