### PR TITLE
Enhance - #90 Refactor strings and status codes

### LINKED ISSUE #90: [ENHANCEMENT] Refactor the hardcoded string values and http status code in the backend
### Description

To refactor the hardcoded string values and https status codes in the controllers and test cases in the backend
image

### Current Behavior

Currently we are hardcoding values like 400, 500, 200 and even the response messages are hardcoded in the `post-controller` and we are using the same hardcoded values in the testcases aswell. We need to refactor this.

### Proposed Enhancement

All the strings should be put in a constants file and http status code should be taken from https://www.npmjs.com/package/http-status-codes, 

### Use Case

Single source of truth and will reduce the margin of errors

### Blockers

_No response_

### Additional Information/ Attachments

_No response_

### PR DESCRIPTION
**Pull request by Imrankhankhattar**
## Summary

Response messages and status codes refactoring (Backend)

## Description

This PR focuses on enhancing the backend by refactoring hardcoded response messages and HTTP status codes. The goal is to improve code maintainability and reduce the risk of errors due to inconsistent values. I have defined the status codes in the constant file already there, and made a new file for the messages, as it will grow over time.

## Issue(s) Addressed

Closes #90

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
@shmbajaj, can you kindly let me know your thoughts on this, LGTM though, wanted your POV.

**Review by shmbajaj — CHANGES_REQUESTED** [review]
Constants and Messages are same thing?
Can we move into constants? @Imrankhankhattar

**Comment by Imrankhankhattar** [comment]
@krishnaacharyaa @shmbajaj I have moved error messages to the constants file.

**Review by krishnaacharyaa — APPROVED** [review]
Thank you for the quick PR @Imrankhankhattar :), LGTM merging now

**Pull request merged**
