### PR TITLE
feat-#57: added markdown support for creating new posts

### LINKED ISSUE #57: Markdown support for creating new posts
### Description

As of now, creating post is just typing plain text in the description box.
This doesn't provide any control over text formatting, like making text bold, italic, or HTML formatting like heading, etc.
It would be a better experience for the writer's as well to be in the control of these things.

### Use Case

As a blog writer
I want to write the content in markdown format, instead of plain text
So that, it'll provide more control in the hands of the writer on how the text should be displayed on UI

### Proposed Solution

_No response_

### Additional Information

_No response_

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by AnirudhMemani**
## Summary

Added markdown support like heading, font family, images, alignment support, hyperlinks etc. for creating new posts.

## Description

+ You can add headings like h1, h2, h3, h4...
+ You can now add images to your blog posts
+ You can now use code blocks, quotes, hyperlinks etc.

- Closes #57

### CODE REVIEW

**Comment by AnirudhMemani** [comment]
@krishnaacharyaa Check it out

**Comment by krishnaacharyaa** [comment]
@AnirudhMemani 
1. Do we need all these options?
2. Black theme highlighted option not able to figure out 
3. Mobile responsiveness is not looking good
4. Let's create new file and not touch add blog tsx
5. Please replace the exisiting css with tailwindcss

**Comment by AnirudhMemani** [comment]
@krishnaacharyaa I will give it a look again. I'm a little busy with some freelance work, one of my clients has an urgent requirement.

**Comment by krishnaacharyaa** [comment]
Sure, please keep us updated. one atleast every 3 days

**Comment by AnirudhMemani** [comment]
@krishnaacharyaa Made changes. Check it out! Sorry for the delay.

**Comment by krishnaacharyaa** [comment]
Its totally fine @AnirudhMemani, thank you for quick response :)
Can we kindly take this up when you are perfectly free and can spend time in this? 
I personally feel, this PR is intended to just finish for the sake of it, because we are missing a lot on attention to details.

Can you let me know when you are free, lets have a call and properly review this thing.

p.s: We have to properly display the exact content with format in the description page as well... so we need to be very careful if the options we are giving is it actually required!!

**Comment by AnirudhMemani** [comment]
@krishnaacharyaa Hey, yeah sorry I have been mad busy with the project. The project will take around 3 months. I'm trying to find time in between and do this. I see the issue, I forgot to change the details page. Can you just list out what options you want me to keep?

**Comment by krishnaacharyaa** [comment]
@AnirudhMemani I totally can relate.. no worries... We'll keep this on hold and pick it when you are back, or totally free...

We would have to discuss, there are quite a few constraints which needs to be considered...
Let's not take it up until you get free time, don't over burden yourself

**Comment by AnirudhMemani** [comment]
@krishnaacharyaa Sure no problem.

**Comment by krishnaacharyaa** [comment]
Closing as inactive

**Pull request closed without merging**
