### PR TITLE
feat: Implemented email based authentication.

### PR DESCRIPTION
**Pull request by Mohitsen11**
## Summary

This PR implements middlware to check user authenticity while creating post.

## Description

This PR solves the backend authenticity problem when user try to create post. If user is authenticate, token is valid or not expired. User can create post.
After adding values to env variables, changes will show.
When a unauthenticated user will try to create post, he/she will get error of 404 that shows access-token is missing.

## Images

_Include any relevant images or diagrams that can help reviewers visualize the changes, if applicable_

## Issue(s) Addressed

_Enter the issue number of the bug(s) that this PR fixes_

- Template should be strictly **Closes <issue_number>**

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
@Mohitsen11 kindly rebase and are we done with this?

**Comment by Mohitsen11** [comment]
> @Mohitsen11 kindly rebase and are we done with this?

Almost done with access-token work.

**Comment by Mohitsen11** [comment]
> > @Mohitsen11 kindly rebase and are we done with this?
> 
> Almost done with access-token work.
I added logout svg icon that work is ongoing.

**Comment by krishnaacharyaa** [comment]
That's awesome, Around 10 pm can we meet and demo the feature

**Comment by Mohitsen11** [comment]
> That's awesome, Around 10 pm can we meet and demo the feature
> 
> p.s: Please rebase the branch and solve the merge conflicts

I made new PR : https://github.com/krishnaacharyaa/wanderlust/pull/160

**Comment by krishnaacharyaa** [comment]
Closing this, as other PR is replacing this

**Pull request closed without merging**
