### PR TITLE
Added Loading Skeleton for the AddBlog Section

### LINKED ISSUE #445: [BUG] Absence of a Proper Loading skeleton for the AddBlog Section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Present  Loader widget is unresponsive and not matching the website theme
Image

### Expected Behavior

The AddBlog section should have a proper loading skeleton that is responsive and theme accurate.

### Reproduction steps

```bash
1. Login in
2. Click on Add Blog button
3. Notice the error
```

### Screenshots

Proposed design
Image

### Logs

_No response_

### Browsers

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by AMS003010**
## Summary

This PR provides a Loading Skeleton for the AddBlog section so that the user has a seamless experience

## Description

AddBlogPostSkeleton Component has been added and has been used to replace the previous Loader component that was used.

## Images
screenshot

## Issue(s) Addressed

Closes #445  
_Enter the issue number of the bug(s) that this PR fixes_

- Template should be strictly **Closes <issue_number>**
- Example: Closes #1

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
image

So now according to your logic, whereever the RequireAuth is used I'll get your this skeleton loading ....!!

**Comment by AMS003010** [comment]
Sorry, I'll fix that

**Comment by AMS003010** [comment]
Actually umashri_meti wants to fix the rest....
Can we do that in a single PR

**Comment by krishnaacharyaa** [comment]
@umashri_meti

**Comment by krishnaacharyaa** [comment]
@MetiUmashri kindly work on top of this PR if you wanna do a combined PR @AMS003010 yes it is possible, please aim to close this soon. As there is nothing much to be done

**Comment by krishnaacharyaa** [comment]
> image
> 
> So now according to your logic, whereever the RequireAuth is used I'll get your this skeleton loading ....!!

@AMS003010 @MetiUmashri this is still not solved even in the newly raised PR :)

**Pull request merged**
