### PR TITLE
fix-#275: Correct the icon color in dark mode

### LINKED ISSUE #275: [BUG] Redirect Icon Color not matches theme.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The redirect icon on Latest posts don't change color with the theme change.

### Expected Behavior

For dark theme is should turn to a lighter color.

### Reproduction steps

```bash
1. Go to 'Landing Page'
2. Scroll down to 'Latest Post'
4. See error
```

### Screenshots

Screenshot (560)
Screenshot (561)

### Logs

_No response_

### Browsers

Firefox, Chrome, Microsoft Edge, Opera

### OS

Windows, Linux

### PR DESCRIPTION
**Pull request by shivansh84ya**
## Summary

This PR aims to correct the icon color in dark mode to ensure consistency with the theme.

## Description

The current implementation of the icon color in dark mode does not match the overall theme, resulting in a less cohesive user interface. This PR addresses this issue by inverting the icon color in dark mode to ensure it aligns with the theme's color scheme.

## Image 

Screenshot 2024-07-03 133952

Screenshot 2024-07-03 134005

## Issue(s) Addressed

Closes #275 Correct the icon color in dark mode

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
Kindly attach image @shivansh84ya in PR description of both themes

**Comment by krishnaacharyaa** [comment]
So that i can merge this @shivansh84ya

**Comment by shivansh84ya** [comment]
Hey @krishnaacharyaa ,
I added the image merge it now!

**Review by krishnaacharyaa — APPROVED** [review]
Thank you @shivansh84ya, thank you for the quick and sweet solution

**Pull request merged**
