### PR TITLE
feat: Handle middleware errors

### PR DESCRIPTION
**Pull request by shivam-sharma7**
## Summary
The error handling middleware allows us to separate our error logic and send responses accordingly. The next() method we discussed in middleware takes us to next middleware/route handler. For error handling, we have the next(err) function.
## Description
_Explain in detail what this PR is all about. This should include the problem you're solving, the approach taken, and any technical details that reviewers need to know._

## Images
_Include any relevant images or diagrams that can help reviewers visualize the changes, if applicable_

## Issue(s) Addressed #46
_Enter the issue number of the bug(s) that this PR fixes_
- Template should be strictly **Closes <issue_number>**
 

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions) ?

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
@shivam-sharma7 Thank you for raising PR, 
Can I respectfully grab your attention to the first guideline of contributing 
"Claiming an Issue: Before you start working on an issue, make sure it's assigned to you. We do this to avoid overlapping efforts and to ensure your hard work doesn't go to waste. Please avoid raising a PR for an issue assigned to someone else."
And it is assigned to DSAghicha, he seems working on this, and has almost finished working on this.

Can you kindly look into any other available issues, or create a own get it assigned to you and then work on it ... That would be really nice....

**Comment by shivam-sharma7** [comment]
@krishnaacharyaa that't automatically linked with my PR, right? I don't know how it's happen and my PR cover different things. Thanks

**Comment by krishnaacharyaa** [comment]
I meant, This seems to solve the issue of https://github.com/krishnaacharyaa/wanderlust/issues/1 which is already assigned....

I suggest you to please create issue is not already available and then get it assigned then raise the relevant PR. Thank you for your efforts, I'm just trying to make sure no one's efforts is gone waste, kindly co-operate 🙂

**Comment by krishnaacharyaa** [comment]
>Hi @shivam-sharma7, this directly is related to https://github.com/krishnaacharyaa/wanderlust/issues/1 and implements the solution which is already proposed in this, kindly pick other issue as previously clearly specified couple of times.
>Thank you
https://github.com/krishnaacharyaa/wanderlust/issues/46#issuecomment-1793638442

**Pull request closed without merging**
