### PR TITLE
enhancement-#102: Refactoring of all the md: to sm:

### LINKED ISSUE #102: [ENHANCEMENT] Refactoring of all the md: to sm:
### Description

We can aim for default classes (mobile), sm (tablet), lg (desktop if explicitly required), and lets refactor all the other classes if it were using md.

### Current Behavior

The current codebase uses the md: prefix for classes to define styling and behavior, presumably targeted at medium-sized devices. The specific styling associated with these classes may be tailored for devices with a medium screen size, such as tablets or devices in a certain resolution range.

### Proposed Enhancement

The proposed enhancement involves refactoring the existing codebase to improve class naming conventions and create a more consistent structure. The main changes include:

Replacing all instances of md: with sm: to better reflect the intended target, focusing on small to medium-sized devices.

### Use Case

The sm: classes, replacing the existing md: classes, would be employed for tablet-sized devices, providing a tailored layout and styling for this category.

### Blockers

_No response_

### Additional Information/ Attachments

_No response_

### PR DESCRIPTION
**Pull request by Chelseasingla1**
## Summary

This PR is for proper naming convention using sm: 

## Description

It was before at some places md: ,now by changing md: to sm:, we can clarify that these styles are targeted not just at medium-sized devices but also at smaller devices like tablets. This adjustment ensures that the styling is more accurately aligned with the intended range of devices.

## Issue(s) Addressed

 Closes #102 

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
Please take care of issues addressed on the PR description, then we are good to merge...

**Comment by Chelseasingla1** [comment]
> Please take care of issues addressed on the PR description, then we are good to merge...

What issues can you please specify

**Comment by krishnaacharyaa** [comment]
Compare the PR I gave you, you'll get it basically you have to trim closes 1 and add yours

**Comment by krishnaacharyaa** [comment]
Sorry @Chelseasingla1 , it even doesn't have the right thing

image

It should be this way

**Comment by Chelseasingla1** [comment]
> Sorry @Chelseasingla1 , it even doesn't have the right thing
> 
> image
> 
> It should be this way

@krishnaacharyaa Can you please check now

**Comment by krishnaacharyaa** [comment]
image
 You had to remove other things in there, I'll edit no issues, kindly take care from next time

**Review by krishnaacharyaa — APPROVED** [review]
LGTM, thank you

**Comment by Chelseasingla1** [comment]
> image You had to remove other things in there, I'll edit no issues, kindly take care from next time

@krishnaacharyaa Yes sir sorry actually the one PR you mentioned, it was still there so i did not remove it.

**Comment by Chelseasingla1** [comment]
> LGTM, thank you

Thanks to you sir for such a great guidance and patience!!!

**Comment by krishnaacharyaa** [comment]
no worries @Chelseasingla1 , congrats for your first contribution. Feel free to take up any other tasks. This time you are experienced 😉😁

**Comment by Chelseasingla1** [comment]
> no worries @Chelseasingla1 , congrats for your first contribution. Feel free to take up any other tasks. This time you are experienced 😉😁

@krishnaacharyaa yes sure sir !!!

**Pull request merged**
