### PR TITLE
feat: Added darktheme for the signup and signin page

### PR DESCRIPTION
**Pull request by Ameerjafar**
## Summary

Added the dark theme for signin and signup page

## Description
we don't have the dark theme for both signin and signup page we only have a dark theme for home page i have added that one also
## Images
signup page
Screenshot 2024-05-25 100600
signin page
Screenshot 2024-05-25 101236

## Issue(s) Addressed

_Enter the issue number of the bug(s) that this PR fixes_

- Template should be strictly **Closes < #329>**
- Example: Closes: #329 

## Prerequisites

- [ yes ] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
Thank you Ameerjafar! Your PR title meets our guidelines.

**Comment by krishnaacharyaa** [comment]
Hello krishnaacharyaa Thank you for your PR. Unfortunately, it doesn't meet our quality checks.

Please ensure you follow our contribution guidelines. The PR title should match the required format.

For example, it should be like: `fix-#124: Added responsiveness to the Home page screen.`

If you have any query kindly check our [contributor guidelines](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md).

**Comment by krishnaacharyaa** [comment]
Hello krishnaacharyaa Thank you for your PR. Unfortunately, it doesn't meet our quality checks.

Please ensure you follow our contribution guidelines. The PR title should match the required format.

For example, it should be like: `fix-#124: Added responsiveness to the Home page screen.`

If you have any query kindly check our [contributor guidelines](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md).

**Comment by krishnaacharyaa** [comment]
Thank you krishnaacharyaa! Your PR title meets our guidelines.

**Comment by krishnaacharyaa** [comment]
Thank you krishnaacharyaa! Your PR title meets our guidelines.

**Comment by krishnaacharyaa** [comment]
Thank you Ameerjafar! Your PR title meets our guidelines.

**Comment by krishnaacharyaa** [comment]
Thank you Ameerjafar! Your PR title meets our guidelines.

**Comment by krishnaacharyaa** [comment]
Thank you Ameerjafar! Your PR title meets our guidelines.

**Comment by krishnaacharyaa** [comment]
Thank you Ameerjafar! Your PR title meets our guidelines.

**Comment by krishnaacharyaa** [comment]
@Ameerjafar can you please check in the other places and see if there is requirement to make the fields even darker? Can you check standards of the dark theme forms, and we can change it everywhere, may be in the next PR, i'm fine with that. just once can you check

**Comment by Ameerjafar** [comment]
@krishnaacharyaa i have just reopned the pr

**Review by krishnaacharyaa — APPROVED** [review]
LGTM merging this, 
For consistency can you please add these newly added variable color to be used in the add-blog page aswell?

image
And make the require changes to add consitency

**Comment by Ameerjafar** [comment]
@krishnaacharyaa ok sir.

**Pull request merged**
