### PR TITLE
Bugfix/109 featured posts card is not inline with the skeleton card

### LINKED ISSUE #109: [BUG] Featured posts card is not inline with the skeleton card (shimmer card)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

image
image

### Expected Behavior

1. Right  Column 2nd row should be removed.
2. Description's height should be increased to match the actual description height
3. Handle for the mobile screen aswell

### Reproduction URL

https://wanderlust-beta.vercel.app/

### Reproduction steps

```bash
1. Navigate to the URL 
2. When posts are initial loaded, we see that the actual content and the card skeleton is not same in the featured posts section
```

### Screenshots

_No response_

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by SohamRoy-01**
## Summary
Fix all the issue of the featured posts card which is not inline with the skeleton card (shimmer card)

## Description

fix the inline issue in the featured Posts of skeleton UI across all devices

## Issue(s) Addressed

-The issue number of the bug(s) that this PR fixes_

- Closes #109 

## Prerequisites

- Yes I followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by SohamRoy-01** [comment]
Hello @krishnaacharyaa, could you please review this? I believe all the issues have been addressed.

**Review by krishnaacharyaa — APPROVED** [review]
LGTM, kindly follow the commit message guidelines from next time as per contributing guidelines :)

**Comment by krishnaacharyaa** [comment]
Thank you for your contribution @SohamRoy-01  :), You there in the discord ?

**Comment by SohamRoy-01** [comment]
Yes, I'm here on Discord. How can I help you?

**Comment by krishnaacharyaa** [comment]
What is your id? in discord?

**Comment by krishnaacharyaa** [comment]
@SohamRoy-01, By discord I meant, wanderlust project's discord.... In the readme we have a discord link

**Comment by SohamRoy-01** [comment]
Username :- bittu0818
Discord ID :- 613819771435089951

**Comment by SohamRoy-01** [comment]
Discord Id : 613819771435089951

**Pull request merged**
