### PR TITLE
fix-#249: Now authenticate users able to create blog post.

### LINKED ISSUE #249: [BUG] Authenticate user is not able to create blog post.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, when an authenticate user tries to create blog post, backend gave response with toastify "Something went wrong. Please try again later". Tokens are present in cookies and they are valid and not expired but still it is not creating the blog post.

### Expected Behavior

It should create blog post with toastify "Blog post successfully created!". Because user is authenticated and tokes are valid and not expired.
And should give toastify "Your session has expired, please login again!" and redirects to homepage with proper conditional rendering.

### Reproduction steps

```bash
1. Go to 'https://wanderlust-beta.vercel.app/'
2. Click on 'Login'
3. Click on 'Create post'
4. Fill the blog form and hit on 'Post blog'
4. See error
```

### Screenshots

Screenshot (108)

### PR DESCRIPTION
**Pull request by 0xmohitsen**
## Summary

This PR allow authenticated users to create blog posts

## Description

This PR addresses an issue where authenticated users were unable to create blog posts despite having valid and unexpired tokens. The problem manifested as an error toast displaying "Something went wrong. Please try again later!" when authenticate users attempted to create a post.

Now authenticate users can create blog post until and unless tokens are valid and unexpired. And if tokens get expired or invalid, we simply display toastify "Your session has expired, please login again!" and redirects to homepage with conditional rendering.

## Issue(s) Addressed

Closes #249 

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Review by Sukomal07 — CHANGES_REQUESTED** [review]
Can you use  toast.promise to show different states (pending, success, error) of the API request.

**Comment by krishnaacharyaa** [comment]
@0xmohitsen @Sukomal07 kindly fix this
https://github.com/krishnaacharyaa/wanderlust/pull/254 is blocked because of this

**Comment by Sukomal07** [comment]
Ok

**Comment by Sukomal07** [comment]
@0xmohitsen change your in this way
`const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (validateFormData()) {
      try {
        const response = axiosInstance.post('/api/posts/', formData);
        toast.promise(response, {
          pending: 'Creating blog ...',
          success: {
            render() {
              setFormData({
                title: '',
                authorName: '',
                imageLink: '',
                categories: [],
                description: '',
                isFeaturedPost: false,
              })
              navigate('/')
              return "Blog created successfully"
            },
          },
          error: {
            render({ data }) {
              if (data instanceof AxiosError) {
                if (data?.response?.data?.message) {
                  return data?.response?.data?.message;
                }
              }
              return "Blog created failed"
            },
          },
        }
        )

        return (await response).data

      } catch (error) {
        if (isAxiosError(error)) {
          console.error(error.response?.data?.message);
        } else {
          console.error(error);
        }
      }
    }
  };`

**Comment by 0xmohitsen** [comment]
> @0xmohitsen change your code in this way
> 
> ` const handleSubmit = async (e: FormEvent) => { e.preventDefault(); if (validateFormData()) { try { const response = axiosInstance.post('/api/posts/', formData); toast.promise(response, { pending: 'Creating blog ...', success: { render() { setFormData({ title: '', authorName: '', imageLink: '', categories: [], description: '', isFeaturedPost: false, }) navigate('/') return "Blog created successfully" }, }, error: { render({ data }) { if (data instanceof AxiosError) { if (data?.response?.data?.message) { return data?.response?.data?.message; } } return "Blog created failed" }, }, } )
> 
> ```
>     return (await response).data
> 
>   } catch (error) {
>     if (isAxiosError(error)) {
>       console.error(error.response?.data?.message);
>     } else {
>       console.error(error);
>     }
>   }
> }
> ```
> 
> }; `

Added this code and tested.

**Review by Sukomal07 — APPROVED** [review]

**Review by krishnaacharyaa — APPROVED** [review]

**Pull request merged**
