### PR TITLE
fix#13: Made the features post responsive for mobile screen size

### PR DESCRIPTION
**Pull request by geetanjalichawla**
## Summary

I have made the featured post section responsive for the mobile devices it used to look like this 
image

which is very messy and not responsive for the mobile sizes/

## Description

fix: Made the features post responsive for mobile screen size

## Images

image
image
## Issue(s) Addressed

_Enter the issue number of the bug(s) that this PR fixes_
#13

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
@geetanjalichawla Thank you for quick PR, couple of observations,
image

In the existing implementation we might have to fix the description a bit, it is getting cut abruptly, and secondly can we solve this issue without any hooks as presently proposed. We can aim to use just the breakpoints for our advantage and make require changes, as discussed in the commit page, we can just make use of `md:` for larger than mobile devices and rest without any prefix would be mobile specific.

So we'll take the above thing for our advantage and avoid using the below hook which would cause overhead for us
```
  const titleRef = useRef(null);

  const [cardHeight, setCardHeight] = useState(28);

  useEffect(() => {
    const titleElement = titleRef.current as unknown as HTMLDivElement;
    const titleHeight = titleElement?.offsetHeight;
    console.log('Title Height:', titleHeight);
    setCardHeight(titleHeight);
  }, [titleRef]); 

```

**Comment by geetanjalichawla** [comment]
@krishnaacharyaa 

1. Thankyou so much to letting me know about that overflow issue in the picture i will for sure fix it in the next commit 
2. Do you want me to remove hook and use max height or just remove the hook and let it be 4 line size 
3. and lastly should i reduce the title line in desktop also ? thats looking messy will share a example screenshot before doing it if you want me to

**Comment by krishnaacharyaa** [comment]
> Do you want me to remove hook and use max height or just remove the hook and let it be 4 line size

Didn't exactly get what you are asking, if i have to clearly convey its basically using breakpoint `md:` (instead of hooks (_above mentioned code snippet_) and sticking to the lines which we discussed along with figma, if the requirements seems unclear kindly ask me.

> and lastly should i reduce the title line in desktop also ? thats looking messy will share a example screenshot before doing it if you want me to

Yeah I understand your concern, we can may be keep it to 2 lines in the desktop and 1 line title for the mobile, that would be easy than too many options, let me know your thoughts, open for it aswell. 

p.s: Let's boil it down to very simple requirement w.r.t mobile and desktop device and then work on the minimal changes required. That way we can make good progress

**Comment by geetanjalichawla** [comment]
image


I was trying to say handling the description using max height with size-sm can cause the issue like you have mentioned in the picture what we can do is just keep the hooks or we can remove that line things here 

image

also i have fixed this issue and removed the hook for now can you suggest me if there is any other way to fix that more description in 1 line tittle

**Pull request closed without merging**
