### PR TITLE
Create greetings.yaml

### PR DESCRIPTION
**Pull request by sanmarg**
Added for #228

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
Hi Mate, you are missing lots of places, please slow down and give attention to detail
1. PR description and commit guidelines is not being followed
2. 
image
Chat gpt /bard gives me this ... You have greeting template going not sure how this is greeting, it is mostly a warning message, I don't want to greet anyone tbh.
3. Please test it before doing a PR.

@Mayur-666 please take care of this use case, it will be challenging but high need https://github.com/krishnaacharyaa/wanderlust/issues/230, test it in your other project and then raise the PR. Because this is the need, I'll revise the acceptance criteria soon for this issue....

**Comment by Mayur-666** [comment]
@krishnaacharyaa I have this one in mind

name: 'Greetings'

on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Welcome Issue
        if: github.event_name == 'issues'
        uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Congratulations, @${{ github.actor }}! 🎉 
            Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!
            We will promptly review your issue and offer feedback. 
            Kindly remember to check our [contributing guidelines(https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md)
      - name: Welcome Pull Request
        if: github.event_name == 'pull_request_target'
        uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Great job, @${{ github.actor }}! 🎉 
            Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.
            We will promptly review your changes and offer feedback.
            Kindly remember to check our [contributing guidelines](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/pull_request_template.md)

**Comment by Mayur-666** [comment]
@krishnaacharyaa  It will be something like this / or we can do some changes in message

Screenshot (537)

**Comment by krishnaacharyaa** [comment]
> @krishnaacharyaa It will be something like this / or we can do some changes in message
> 
> Screenshot (537)

LGTM, we'll change the message, not getting if it is the issue wala or the PR wala... ig you wantedly just tried both the things
Lets focus on the PR raised github action first... and if @sanmarg doesn't reply quick enough post #230 issue you can take others in the sequence as well.

In #230 there are many other factors, written neatly in the acceptance criteria, can you kindly look into that.
You can raise 1 by 1 I'm fine with that...
I just need those acceptance criteria to be fullfilled... Shall we now work on that then?

**Comment by krishnaacharyaa** [comment]
@Mayur-666

**Comment by Mayur-666** [comment]
Yes sure @krishnaacharyaa

**Comment by krishnaacharyaa** [comment]
ig you have picked it from here https://github.com/Sanchitbajaj02/palettegram/issues/306
Thats good, we need to check what are others upto, 

He has used some bots in the PR as well, can you look into that? And see if even we can leverage that kinda thing.
Very similar to what we are looking for 
@Mayur-666

**Comment by Mayur-666** [comment]
well i have taken it from swapnil, he's my friend and we made that at time of social summer of code.

**Comment by krishnaacharyaa** [comment]
@Mayur-666 Then I guess this guy has taken from swapalin aswell 😂😂
Well it's never a problem for me ...
I'm happy to know you are part of the root thing or closely related ...
I thoo copy from everywhere possibly and do it ☺️. That's how we all learn

**Comment by rudi-cilibrasi** [comment]
@sanmarg i saw you like docker in your blog. this project uses Docker for cicd but it only does one kind of build using clang-12. it needs to also install react or vite dependencies in the docker image and then devs can run the react or vite frontend webserver using docker with a tcp port hole punch in say port 3000 or maybe --net=host

i just wanted to mention the need to you in case you are interested. there is also a need for an emscripten build (in addition to the clang-12 build we already check in cicd) to go into the react/vite frontend. ideally devs can then run docker container locally to see the changes they are making work etc

**Pull request closed without merging**
