### PR TITLE
fix-#397: fixed view password button alignment

### LINKED ISSUE #397: [BUG] <View Password Icon Alignment Bug>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

View password alignment issues
Screenshot (95)

### Expected Behavior

It should be aligned properly in the password input tag

Can you assign me this issue under gssoc 2024

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

DESCRIPTION
Screenshot (95)

### Logs

_No response_

### Browsers

_No response_

### OS

Windows

### PR DESCRIPTION
**Pull request by vamsidhar-914**
## Summary

fixed view password alignment icon 

## Images

Screenshot (193)

mobile view
Screenshot (199)

## Issue(s) Addressed

Closes #397 

## Prerequisites

- [ yes] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by vamsidhar-914** [comment]
@krishnaacharyaa

**Comment by krishnaacharyaa** [comment]
Kindly add image of the mobile view aswell

**Comment by vamsidhar-914** [comment]
added!

**Review by krishnaacharyaa — APPROVED** [review]
Thank you for the changes :)

**Pull request merged**
