### PR TITLE
BUGFIX-#193: User can access undefined routes.

### LINKED ISSUE #193: [BUG] User can access undefined routes.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, when a user tries to hit routes like "https://wanderlust-beta.vercel.app/hgdf" ( "https://wanderlust-beta.vercel.app/undefined-routes") the application does not handle undefined routes gracefully and simply displays a page which displays footer.

Screenshot 2024-05-11 153527

### Expected Behavior

When navigating to undefined routes such as http://localhost:3000/iughdfugh, I expect to be redirected to a 404 Page Not Found error page. 

Reference Imag
error-page
e:-

### Reproduction steps

```bash
1. Go to 'https://wanderlust-beta.vercel.app/'
2. Search on 'https://wanderlust-beta.vercel.app/whatever-you-like'
3. See error
```

### Screenshots

DESCRIPTION

### Logs

```bash
Steps to Implement:

1. Create a 404 Page Not Found component if not already existing. This component should display a user-friendly message informing users that the requested page cannot be found.
2. Define a route for undefined paths in the router configuration (e.g., React Router). This route should match any undefined paths and render the 404 Page Not Found component.
3. When a user navigates to an undefined route, the router should automatically redirect them to the 404 Page Not Found component.
4. Test the implementation thoroughly to ensure that accessing undefined routes correctly redirects users to the 404 error page.
5. Add appropriate styling and design to the 404 Page Not Found component to enhance user experience.
```

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by Mayur-666**
## Summary
Added  404 not found page.

## Issue(s) Addressed

 Closes #193 

## Prerequisites

- [ Yes] Have you followed all the [CONTRIBUTING GUIDELINES]

### CODE REVIEW

**Comment by Mayur-666** [comment]
Finally, I have done all the changes.

**Comment by krishnaacharyaa** [comment]
LGTM , just couple of changes, if I may
image

Here can we add something like a black overlay , because in dark mode the "Not Found" is not very evident, it is getting shadowed by the moving things. So that will make it effective.
And Please make the title to Page Not Found 

And instead of the back button, make it Go to Home and have just p-4 or p-8 whichever looks good.

Rest LGTM

**Comment by Mayur-666** [comment]
The blur thing is not working on them, i can change the color of links if you think it'll be right, 
like this

Screenshot (534)

**Comment by krishnaacharyaa** [comment]
Yeah some where in between gray and white , this is a bit tooo dark grey, make it a little lighter and subtle, take a call

**Comment by Mayur-666** [comment]
yes from #666666 to #aaaaaa like this one

Screenshot (535)

**Comment by Mayur-666** [comment]
Should i commit then

**Comment by krishnaacharyaa** [comment]
Go ahead

**Comment by Mayur-666** [comment]
I have done the suggested changes! @krishnaacharyaa

**Comment by Mayur-666** [comment]
GIT brought me headache, i wasn't sure how to make the two commit into one, just now i learned more about git, this project made upskilled me in git 👍🏻

**Review by krishnaacharyaa — APPROVED** [review]
LGTM, thanks

**Comment by Mayur-666** [comment]
Thank you for merging, it has excited me to contribute to this project more.

**Comment by krishnaacharyaa** [comment]
Thank you @Mayur-666, And are you interested in some challenges? I have some issues, it might interest you

**Comment by Mayur-666** [comment]
@krishnaacharyaa  Sure bro, without saying.

**Comment by krishnaacharyaa** [comment]
@Mayur-666 
Basically it's about creation of github-actions.
Because of this GSSoC i want to automate some manual stuffs, like say.

1. As soon as issue is created, it should say "Hi <author-name>, hope you have followed the code of conduct, if it doesn't follow we'll close this issue" and additionally it should also ai generation checks if possible 
2. As soon as the PR is raised, it should check the PR content see some regex basically our format and check the commits for the community guidelines and prompt saying you have not followed the code guidelines bla bla

Something around this, i know this will be challenging, but this will be really interesting issue if we can come up with a solution.

Can you take this up @Mayur-666 , it would involve little research , and would add good level of experience to you even, 
This is the need now... 
We can anyways give more points by splitting the tasks, I guess by now you know I'm not a strict teacher, i just give marks 😂

**Comment by Mayur-666** [comment]
wow nice idea, let's see how far we can get on it.
By the way, thannnnk youuu teacher 🤣 @krishnaacharyaa

**Comment by krishnaacharyaa** [comment]
@Mayur-666  sure! please raise issue for the first one , will assign it to you. The faster we do better it is :)
We'll split into 4 issues.
1. 
2. 
3. 
4. Ai generated text detection we'll do here.
Rest all as above...
Done ?

**Pull request merged**
