### PR TITLE
Bug- #108 inlining all posts card with skeleton

### LINKED ISSUE #108: [BUG] All posts card is not inline with the skeleton (shimmer card)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

image

image

### Expected Behavior

1. Title and description should be full, with some padding at right
2. Reduce the gap between the categories shimmer in the last row
3. Handle for the mobile screen aswell

### Reproduction URL

https://wanderlust-beta.vercel.app/

### Reproduction steps

```bash
1. Navigate to the URL 
2. When posts are initial loaded, we see that the actual content and the card skeleton is not same
```

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by Chelseasingla1**
## Summary

To inline the posts according to skeleton.

## Description

This PR is according to changes made in post-card-skeleton to make padding properly, and making changes to handle properly in all the screens, a little changes are made for last row to make it look more interactive.

## Images
image

## Issue(s) Addressed

Closes #108 

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
This will be interesting learning for you 

image

Why did the previous message has come here? 
1. either you didn't create a new branch
2. You created a branch from the previous branch.
3 you have to ideally come back to the main branch, sync it with upstream
4. then create new branch and then commit

Try to figure this out you'll learn a lot :)
I guess you are in the 2nd wrong wala one 

image


Closing this one for now as it doesn't follow the guidelines

**Comment by Chelseasingla1** [comment]
@krishnaacharyaa so i need to make a new branch in my repo to match with yours right then raise the PR, because i did pull the main branch it was upto date

**Comment by krishnaacharyaa** [comment]
@Chelseasingla1 
Yeah, never commit in main branch

Now reset your branch to be in sync with the upstream branch i.e this wanderlust branch
And then create a feature-branch which you want to raise PR and then raise that branch as a PR. 
For new issue new PR it goes that way, closely read the contributing guidelines, it has everything nicely there, 
You can play around for more knowledge with chatgpt

**Comment by Chelseasingla1** [comment]
> @Chelseasingla1 Yeah, never commit in main branch
> 
> Now reset your branch to be in sync with the upstream branch i.e this wanderlust branch And then create a feature-branch which you want to raise PR and then raise that branch as a PR. For new issue new PR it goes that way, closely read the contributing guidelines, it has everything nicely there, You can play around for more knowledge with chatgpt

@krishnaacharyaa okay sir thankyou i will keep that in mind.

**Pull request closed without merging**
