### PR TITLE
Solve the Image error msg and Category selection issue

### PR DESCRIPTION
**Pull request by MrBlackGhostt**
## Summary
The issue pertains to the category selection in form validation and the image url. The goal is to allow users to select 3 or more categories and trigger a validation error if fewer than 3 categories are selected.

## Description

Solve the issue of Category selection in the form validation

categories: z.array(z.string()).refine((value) => value.length >= 3, {
    message: 'Easy there! Select up to 3 categories.',
  }),

## Images

Before:-
Screenshot 2023-12-17 at 11 10 10 AM

After:-
Screenshot 2023-12-17 at 11 10 31 AM

## Issue(s) Addressed

issue #83

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
Can you rebase this PR @MrBlackGhostt.

**Comment by krishnaacharyaa** [comment]
Closing it as it is inactive for a while now

**Comment by MrBlackGhostt** [comment]
I am on a holiday @krishnaacharyaa  that why I inactive can you tell me what things need to be update

**Comment by krishnaacharyaa** [comment]
@MrBlackGhostt, we would have to update the branch to latest changes and also make sure that there is no impact on the exisiting features

**Comment by MrBlackGhostt** [comment]
ok i check there would not be any error

**Pull request closed without merging**
